# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Backend CI/CD (Spring Boot)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # --------------------------------------------------
  # JOB 1: BUILD & TEST
  # --------------------------------------------------
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package -DskipTests --file pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


  # --------------------------------------------------
  # JOB 2: BUILD & PUSH DOCKER IMAGE
  # --------------------------------------------------
  docker:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build & Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')/backend:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME


  # --------------------------------------------------
  # JOB 3: DEPLOY (Proxmox + Tailscale)
  # --------------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    environment: Production
    timeout-minutes: 5

    steps:
    - name: Tailscale Connect
      #uses: tailscale/github-action@v2
      with:
        #oauth-client-id: ${{ secrets.CLIENT_ID_TAILSCALE }}
        oauth-secret: ${{ secrets.CLIENT_SECRET_TAILSCALE }}
        tags: tag:ci-runner
        version: 1.88.1

    - name: Deploy Backend via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.URL_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |
          echo "ðŸ”µ [Deploy BK] Conectado al servidor..."

          USERNAME="${{ secrets.GHCR_USERNAME }}"
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG="ghcr.io/$USERNAME/$REPO_NAME/backend:latest"
          CONTAINER_NAME="country-app-backend"

          echo "ðŸ”µ Login GHCR"
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "$USERNAME" --password-stdin

          echo "ðŸ”µ Pull imagen backend"
          docker pull $IMAGE_TAG

          echo "ðŸ”µ Stop contenedor viejo"
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          echo "ðŸ”µ Run backend"
          docker run -d \
            --name $CONTAINER_NAME \
            -p 8081:8080 \
            --restart always \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASS=${{ secrets.DB_PASS }} \
            $IMAGE_TAG

          docker image prune -f
          echo "âœ… Backend desplegado correctamente"
